color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.844594
  lightness: 0.698198
  rhythmicContrast: 0.786036
  saturation: 0.751126
layout_spectrum: 0.407657
name: 'malek store '
typography_spectrum: 0.796171
