color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.136261
  lightness: 0.287162
  rhythmicContrast: 0.307432
  saturation: 0.207207
layout_spectrum: 0.407657
name: 'malek store '
typography_spectrum: 1
