color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.674549
  lightness: 0.513513
  rhythmicContrast: 0.51126
  saturation: 0.502252
layout_spectrum: 0.407657
name: 'malek store '
typography_spectrum: 0.977477
