layout_spectrum: 0.4007294313889919
typography_spectrum: 0.2782483442550949
color:
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  brandStrength: 0.3258149856533671
  lightness: 0.22789879641661623
  saturation: 0.9843911337645005
  rhythmicContrast: 0.44939563036628877
coverPrefs:
  filter: false
name: 'malek store '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6b16dd9b-ffc9-4cc4-96e5-035223c7db4a.jpg
cta: {}
analytics:
  facebook: ''
  google: UA-80814309-2
  twitter: ''
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/963c7d3f-caf6-4e68-b9cb-9fa27ca67b3a.jpg
purpose:
  - type: contact
    label: Call 01100542030
    url: 'tel:01100542030'
title: MALEK STORE
description: ''
author: {}
content_rating:
  adult: false
navigation:
  - name: 'Our Facebook page '
    url: 'https://www.facebook.com/abumalekstore/'
    type: external
content: []
github: true
