color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.675675
  lightness: 0.489864
  rhythmicContrast: 0.70045
  saturation: 0.479729
layout_spectrum: 0.407657
name: 'malek store '
typography_spectrum: 0.796171
