color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.674549
  lightness: 0.372747
  rhythmicContrast: 0.378378
  saturation: 0.346846
layout_spectrum: 0.407657
name: 'malek store '
typography_spectrum: 0.977477
